format:
  revealjs:
    theme: [default, theme.scss]
    css: custom.css
    transition: fade
    background-transition: fade
    highlight-style: arrow
    fontsize: 1.5em
    code-line-numbers: false
code-link: true
execute:
  echo: true
  freeze: auto
